{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "New Panel",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{source=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percent{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Percentage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage_percent{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizza_revenue_USD_total{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Purchase Attempts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pizzas_sold_total{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "Pizzas Sold in the Last Minute"
    },
    {
     "expr": "pizza_creation_failures_total{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza Creation Failures in the Last Minute"
    }
   ]
  },
  {
   "title": "Http Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "http_requests_per_minute_ratio{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication Attempts Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "auth_success_per_minute_ratio{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "Successful Authentications in the Last Minute"
    },
    {
     "expr": "auth_failure_per_minute_ratio{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "Unsuccessful Authentications in the Last Minute"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "active_users_ratio{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "service_endpoint_latency_ms_avg_milliseconds{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "Service Request Latency"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 10, "y": 26 },
   "targets": [
    {
     "expr": "pizza_creation_latency_ms_avg_milliseconds{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza Creation Service Latency"
    }
   ]
  }
 ]
}